[tool.poetry]
name = "function-calling"
version = "0.1.0"
description = ""
authors = ["anouar taizoukt <ataizoukt@leyton.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
streamlit = "^1.41.1"
openai = "^1.61.0"


